# Generated by Django 5.2.6 on 2025-10-01 11:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_hostel_4', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('delta_3', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10)),
                ('delta_2', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10)),
                ('delta_1', models.DecimalField(decimal_places=2, default=Decimal('3500.00'), max_digits=10)),
                ('ac_addon', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('base_mess', models.DecimalField(decimal_places=2, default=Decimal('4500.00'), max_digits=10)),
                ('rebate_min_days', models.PositiveIntegerField(default=4)),
                ('mess_per_day', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('default_due_day', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeeMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mess_absent_days', models.PositiveIntegerField(default=0)),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('base_mess_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mess_rebate_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_mess_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fine_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('is_rebate_eligible', models.BooleanField(default=False)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'student_id'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], default='online', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feemonth')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='fees.feemonth')),
            ],
        ),
    ]
