# Generated by Django 5.2.6 on 2025-09-16 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_alter_room_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messattendance',
            options={'ordering': ['-date', 'meal_type'], 'verbose_name': 'Mess Attendance', 'verbose_name_plural': 'Mess Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='roomattendance',
            options={'ordering': ['-date'], 'verbose_name': 'Room Attendance', 'verbose_name_plural': 'Room Attendance Records'},
        ),
        migrations.RemoveField(
            model_name='messattendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='roomattendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='messattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
        migrations.AddField(
            model_name='roomattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('room', 'Room'), ('mess', 'Mess')], max_length=10)),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Notification',
                'verbose_name_plural': 'Attendance Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_present_count', models.IntegerField(default=0)),
                ('room_absent_count', models.IntegerField(default=0)),
                ('mess_present_count', models.IntegerField(default=0)),
                ('mess_absent_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Statistics',
                'verbose_name_plural': 'Attendance Statistics',
            },
        ),
    ]
