# Generated by Django 5.2.6 on 2025-09-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_room_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('complaint', 'Complaint'), ('cleaning', 'Room Cleaning'), ('leave', 'Leave Request'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('from_date', models.DateField(blank=True, help_text='For leave requests', null=True)),
                ('to_date', models.DateField(blank=True, help_text='For leave requests', null=True)),
                ('leave_reason', models.TextField(blank=True, help_text='For leave requests')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact for leave', max_length=15)),
                ('cleaning_type', models.CharField(blank=True, help_text='Type of cleaning', max_length=50)),
                ('preferred_date', models.DateField(blank=True, help_text='For cleaning requests', null=True)),
                ('preferred_time', models.CharField(blank=True, help_text='morning/afternoon/evening', max_length=20)),
                ('complaint_category', models.CharField(blank=True, help_text='Category of complaint', max_length=50)),
                ('urgency_level', models.CharField(blank=True, help_text='Urgency level', max_length=20)),
                ('room_number', models.CharField(blank=True, help_text='Room number if applicable', max_length=10)),
                ('warden_response', models.TextField(blank=True, help_text="Warden's response or notes")),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Warden who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Request',
                'verbose_name_plural': 'Student Requests',
                'db_table': 'student_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('request_update', 'Request Update'), ('general', 'General'), ('urgent', 'Urgent'), ('announcement', 'Announcement')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_notifications', to='students.student')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.studentrequest')),
            ],
            options={
                'verbose_name': 'Request Notification',
                'verbose_name_plural': 'Request Notifications',
                'db_table': 'request_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
